/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SelgRouteImport } from './routes/selg'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BilerIndexRouteImport } from './routes/biler.index'
import { Route as BilerIdRouteImport } from './routes/biler.$id'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'
import { Route as ApiPublicFinnListingsRouteImport } from './routes/api/public/finn.listings'
import { Route as ApiPublicFinnAdIdRouteImport } from './routes/api/public/finn.ad.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelgRoute = SelgRouteImport.update({
  id: '/selg',
  path: '/selg',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilerIndexRoute = BilerIndexRouteImport.update({
  id: '/biler/',
  path: '/biler/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilerIdRoute = BilerIdRouteImport.update({
  id: '/biler/$id',
  path: '/biler/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFinnListingsRoute = ApiPublicFinnListingsRouteImport.update({
  id: '/api/public/finn/listings',
  path: '/api/public/finn/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFinnAdIdRoute = ApiPublicFinnAdIdRouteImport.update({
  id: '/api/public/finn/ad/$id',
  path: '/api/public/finn/ad/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/selg': typeof SelgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/biler/$id': typeof BilerIdRoute
  '/biler/': typeof BilerIndexRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/finn/listings': typeof ApiPublicFinnListingsRoute
  '/api/public/finn/ad/$id': typeof ApiPublicFinnAdIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/selg': typeof SelgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/biler/$id': typeof BilerIdRoute
  '/biler': typeof BilerIndexRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/finn/listings': typeof ApiPublicFinnListingsRoute
  '/api/public/finn/ad/$id': typeof ApiPublicFinnAdIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/selg': typeof SelgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/biler/$id': typeof BilerIdRoute
  '/biler/': typeof BilerIndexRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/finn/listings': typeof ApiPublicFinnListingsRoute
  '/api/public/finn/ad/$id': typeof ApiPublicFinnAdIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/om-oss'
    | '/selg'
    | '/sitemap.xml'
    | '/biler/$id'
    | '/biler/'
    | '/api/public/lead'
    | '/api/public/finn/listings'
    | '/api/public/finn/ad/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/om-oss'
    | '/selg'
    | '/sitemap.xml'
    | '/biler/$id'
    | '/biler'
    | '/api/public/lead'
    | '/api/public/finn/listings'
    | '/api/public/finn/ad/$id'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/om-oss'
    | '/selg'
    | '/sitemap.xml'
    | '/biler/$id'
    | '/biler/'
    | '/api/public/lead'
    | '/api/public/finn/listings'
    | '/api/public/finn/ad/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  SelgRoute: typeof SelgRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BilerIdRoute: typeof BilerIdRoute
  BilerIndexRoute: typeof BilerIndexRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
  ApiPublicFinnListingsRoute: typeof ApiPublicFinnListingsRoute
  ApiPublicFinnAdIdRoute: typeof ApiPublicFinnAdIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selg': {
      id: '/selg'
      path: '/selg'
      fullPath: '/selg'
      preLoaderRoute: typeof SelgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biler/': {
      id: '/biler/'
      path: '/biler'
      fullPath: '/biler/'
      preLoaderRoute: typeof BilerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biler/$id': {
      id: '/biler/$id'
      path: '/biler/$id'
      fullPath: '/biler/$id'
      preLoaderRoute: typeof BilerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/finn/listings': {
      id: '/api/public/finn/listings'
      path: '/api/public/finn/listings'
      fullPath: '/api/public/finn/listings'
      preLoaderRoute: typeof ApiPublicFinnListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/finn/ad/$id': {
      id: '/api/public/finn/ad/$id'
      path: '/api/public/finn/ad/$id'
      fullPath: '/api/public/finn/ad/$id'
      preLoaderRoute: typeof ApiPublicFinnAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  SelgRoute: SelgRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BilerIdRoute: BilerIdRoute,
  BilerIndexRoute: BilerIndexRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
  ApiPublicFinnListingsRoute: ApiPublicFinnListingsRoute,
  ApiPublicFinnAdIdRoute: ApiPublicFinnAdIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
